language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
script: cd vk_generator
env:
  global:
    secure: KZBWOVHTyaxLsUG8Ja2NfgOrwYLtruRU7u5hwxNJU5md2mfKTkbfgVd/FJM/et2Q7vLxnmkN2gir+0dW6MxAy/lAcWzX2fpJBTUnwX9DwvMVHm38pV1ygUkUNNoVCB1Y0kgzAwBQfSZUcf0uXjk8lEsj5bttP156hnowYAgzBSReq3hJ4mquODb2exwhxUPRNcjJL6HuA5tpwT3tIUWnbEpZ0o+arC2eeJ+HUeOI46q6PEZ8r1mpJR708SCZnenRtmKmPCxQxgqPUxSiNS6tDSg699dc2dgb7rI2dHeBln5pRBt9VuuVKXm+dknoxUWEFUXqOCl55LA9OunWSRJcoQXDcouPDb/ZYt42wWBhfbU8d1B95o9D2dXDv/EAHpNeQmGdhckxpPMs8dnA05zVCw+gYPyFmb8bqz3CNaZz2DARWy8JS8r0y76Vn6SJ0uwtc3sVznQ3ExkpLwtrozlP2EDUxColuJGr4II17KlwqRLlZo7++YgKLmAjBI5BbLSUAZAS7/3lE3HRb5sc/zINahZFUu845HBptN2sknhjL/ftGw1hj5xzGeb6akworNyLxVq4r1Lw9T1gZy1gynNqUkowRt4fWrnZSSPJ1Ijh3P7+6lGH1pFAK5Cng4oYzCiXvlZj1yhGzCiGezPuMirXgd75ytpdHjZSoKlh67DDhYU=
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages